spring:
  datasource:
    url: jdbc:mysql://localhost:6033/mtg
    username: root
    password: root
    driver-class-name: 'com.mysql.cj.jdbc.Driver'

  liquibase:
    url: jdbc:mysql://localhost:6033/mtg
    user: root
    password: root
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    default-schema: mtg
    change-log: classpath:db.changelog-master.yaml
#  kafka:
#    consumer:
#      group-id: service
#      auto-offset-reset: earliest
#    producer:
#      bootstrap-servers: localhost:9092