spring:
  datasource:
    url: jdbc:mysql://localhost:6033/aetherbase
    username: root
    password: root
    driver-class-name: 'com.mysql.cj.jdbc.Driver'

  liquibase:
    default-schema: aetherbase
    change-log: classpath:db/changelog/db.changelog-master.yaml
#    change-log: ./db/changelog/db.changelog-master.yaml
#  kafka:
#    consumer:
#      group-id: service
#      auto-offset-reset: earliest
#    producer:
#      bootstrap-servers: localhost:9092